AllCops:
  TargetRubyVersion: 2.3

# Metrics

Metrics/LineLength:
  Max: 84
  Details: >-
    Line length of 80 is ideal for readability and compatibility; we'll accept
    an extra 4 for minor edge cases (e.g. copyright notice).

Metrics/MethodLength:
  Max: 35

Metrics/BlockNesting:
  Max: 5

Metrics/AbcSize:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/BlockLength:
  Max: 300

# Style

Style/StringLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Not:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/NumericPredicate:
  Enabled: false  # Not compatible with <= 2.2

Style/YodaCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Layout

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false


